/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/reserves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of Reserve resources.
         * @description Retrieves the collection of Reserve resources.
         */
        get: operations["api_reserves_get_collection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reserves/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a Reserve resource.
         * @description Retrieves a Reserve resource.
         */
        get: operations["api_reserves_address_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A representation of common errors. */
        Error: {
            /** @description A short, human-readable summary of the problem. */
            readonly title?: string | null;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            readonly detail?: string | null;
            /**
             * @default 400
             * @example 404
             */
            status: number | null;
            /** @description A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
            readonly instance?: string | null;
            /** @description A URI reference that identifies the problem type */
            readonly type?: string;
        };
        /** @description A representation of common errors. */
        "Error.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /** @description A short, human-readable summary of the problem. */
            readonly title?: string | null;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            readonly detail?: string | null;
            /**
             * @default 400
             * @example 404
             */
            status: number | null;
            /** @description A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
            readonly instance?: string | null;
            /** @description A URI reference that identifies the problem type */
            readonly type?: string;
            readonly description?: string | null;
        };
        HealthCheck: {
            /** @description e.g. STALE, NO_FALLBACK, DEPRECATED_PROVIDER, EMPTY_PRICE_ENTRY, SOURCES_DIVERGE. */
            code?: string;
            /** @enum {string} */
            severity?: "ok" | "info" | "warning" | "critical";
            message?: string;
        };
        "HealthCheck.jsonld": {
            /** @description e.g. STALE, NO_FALLBACK, DEPRECATED_PROVIDER, EMPTY_PRICE_ENTRY, SOURCES_DIVERGE. */
            code?: string;
            /** @enum {string} */
            severity?: "ok" | "info" | "warning" | "critical";
            message?: string;
        };
        HydraCollectionBaseSchema: components["schemas"]["HydraCollectionBaseSchemaNoPagination"] & {
            /**
             * @example {
             *       "@id": "string",
             *       "@type": "string",
             *       "first": "string",
             *       "last": "string",
             *       "previous": "string",
             *       "next": "string"
             *     }
             */
            view?: {
                /** Format: iri-reference */
                "@id"?: string;
                "@type"?: string;
                /** Format: iri-reference */
                first?: string | null;
                /** Format: iri-reference */
                last?: string | null;
                /** Format: iri-reference */
                previous?: string | null;
                /** Format: iri-reference */
                next?: string | null;
            };
        };
        HydraCollectionBaseSchemaNoPagination: {
            totalItems?: number;
            search?: {
                "@type"?: string;
                template?: string;
                variableRepresentation?: string;
                mapping?: {
                    "@type"?: string;
                    variable?: string;
                    property?: string | null;
                    required?: boolean;
                }[];
            };
        };
        HydraItemBaseSchema: {
            "@context"?: string | ({
                "@vocab": string;
                /** @enum {string} */
                hydra: "http://www.w3.org/ns/hydra/core#";
            } & {
                [key: string]: unknown;
            });
            "@id": string;
            "@type": string;
        };
        MarketRef: {
            /** @description Lending market address on Solana. */
            address?: string;
            /** @description Name shown by the protocol's own app; null for unlisted (permissionless) markets. */
            name?: string | null;
        };
        "MarketRef.jsonld": {
            /** @description Lending market address on Solana. */
            address?: string;
            /** @description Name shown by the protocol's own app; null for unlisted (permissionless) markets. */
            name?: string | null;
        };
        OracleAccounts: {
            /** @description Scope price account (Kamino's oracle aggregator). */
            scopePrices?: string | null;
            /** @description Entries of the Scope price account multiplied together to get the price. */
            scopeChain?: number[];
            pyth?: string | null;
            switchboard?: string | null;
        };
        "OracleAccounts.jsonld": {
            /** @description Scope price account (Kamino's oracle aggregator). */
            scopePrices?: string | null;
            /** @description Entries of the Scope price account multiplied together to get the price. */
            scopeChain?: number[];
            pyth?: string | null;
            switchboard?: string | null;
        };
        PriceStatus: {
            /** @description Age of the oldest price in the reserve's price chain; null when it could not be read. */
            ageSeconds?: number | null;
            /** @description The protocol's own limit: older prices are rejected. */
            maxAgeSeconds?: number;
            /** @description True when the price is older than the protocol accepts. */
            isStale?: boolean;
        };
        "PriceStatus.jsonld": {
            /** @description Age of the oldest price in the reserve's price chain; null when it could not be read. */
            ageSeconds?: number | null;
            /** @description The protocol's own limit: older prices are rejected. */
            maxAgeSeconds?: number;
            /** @description True when the price is older than the protocol accepts. */
            isStale?: boolean;
        };
        /** @description Lending reserves with their oracle health, filterable and sortable. */
        Reserve: {
            /** @description Reserve / bank account address on Solana. */
            address?: string;
            /** @description Lending protocol, e.g. "kamino". */
            protocol?: string;
            /** @description Token symbol as configured by the protocol, e.g. "SOL". */
            asset?: string;
            mint?: string;
            market?: components["schemas"]["MarketRef"];
            /** @description active, obsolete or hidden. */
            status?: string;
            /** @description Deposited value (available + borrowed) in USD, at the protocol's last stored price. */
            totalSupplyUsd?: number;
            /** @description 0 (broken) to 100 (healthy). */
            score?: number;
            /**
             * @description Worst severity among the failed checks, or "ok" when none failed.
             * @enum {string}
             */
            severity?: "ok" | "info" | "warning" | "critical";
            price?: components["schemas"]["PriceStatus"];
            /** @description Oracle providers the price ultimately comes from, e.g. ["PythLazer", "Chainlink"]. */
            providers?: string[];
            checks?: components["schemas"]["HealthCheck"][];
            oracleAccounts?: components["schemas"]["OracleAccounts"];
            /** Format: date-time */
            checkedAt?: string;
        };
        /** @description Lending reserves with their oracle health, filterable and sortable. */
        "Reserve.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /** @description Reserve / bank account address on Solana. */
            address?: string;
            /** @description Lending protocol, e.g. "kamino". */
            protocol?: string;
            /** @description Token symbol as configured by the protocol, e.g. "SOL". */
            asset?: string;
            mint?: string;
            market?: components["schemas"]["MarketRef.jsonld"];
            /** @description active, obsolete or hidden. */
            status?: string;
            /** @description Deposited value (available + borrowed) in USD, at the protocol's last stored price. */
            totalSupplyUsd?: number;
            /** @description 0 (broken) to 100 (healthy). */
            score?: number;
            /**
             * @description Worst severity among the failed checks, or "ok" when none failed.
             * @enum {string}
             */
            severity?: "ok" | "info" | "warning" | "critical";
            price?: components["schemas"]["PriceStatus.jsonld"];
            /** @description Oracle providers the price ultimately comes from, e.g. ["PythLazer", "Chainlink"]. */
            providers?: string[];
            checks?: components["schemas"]["HealthCheck.jsonld"][];
            oracleAccounts?: components["schemas"]["OracleAccounts.jsonld"];
            /** Format: date-time */
            checkedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_reserves_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
                /** @description The number of items per page */
                itemsPerPage?: number;
                /** @description e.g. kamino */
                protocol?: string;
                /** @description e.g. kamino */
                "protocol[]"?: string[];
                /** @description Lending market address */
                market?: string;
                /** @description Lending market address */
                "market[]"?: string[];
                /** @description Part of the market name */
                marketName?: string;
                /** @description Part of the market name */
                "marketName[]"?: string[];
                /** @description true: only markets listed in the protocol's own app. Unlisted (permissionless) markets can hold tokens with arbitrary prices. */
                listed?: boolean;
                /** @description true: only markets listed in the protocol's own app. Unlisted (permissionless) markets can hold tokens with arbitrary prices. */
                "listed[]"?: boolean[];
                /** @description Part of the asset symbol */
                asset?: string;
                /** @description Part of the asset symbol */
                "asset[]"?: string[];
                /** @description active, obsolete or hidden */
                status?: string;
                /** @description active, obsolete or hidden */
                "status[]"?: string[];
                /** @description e.g. score[lt]=50 */
                "score[gt]"?: {
                    gt?: string;
                    gte?: string;
                    lt?: string;
                    lte?: string;
                    ne?: string;
                    between?: string;
                };
                /** @description e.g. score[lt]=50 */
                "score[gte]"?: {
                    gt?: string;
                    gte?: string;
                    lt?: string;
                    lte?: string;
                    ne?: string;
                    between?: string;
                };
                /** @description e.g. score[lt]=50 */
                "score[lt]"?: {
                    gt?: string;
                    gte?: string;
                    lt?: string;
                    lte?: string;
                    ne?: string;
                    between?: string;
                };
                /** @description e.g. score[lt]=50 */
                "score[lte]"?: {
                    gt?: string;
                    gte?: string;
                    lt?: string;
                    lte?: string;
                    ne?: string;
                    between?: string;
                };
                /** @description e.g. score[lt]=50 */
                "score[ne]"?: {
                    gt?: string;
                    gte?: string;
                    lt?: string;
                    lte?: string;
                    ne?: string;
                    between?: string;
                };
                /** @description e.g. score[lt]=50 */
                "score[between]"?: {
                    gt?: string;
                    gte?: string;
                    lt?: string;
                    lte?: string;
                    ne?: string;
                    between?: string;
                };
                /** @description e.g. totalSupplyUsd[gte]=100000 */
                "totalSupplyUsd[gt]"?: {
                    gt?: string;
                    gte?: string;
                    lt?: string;
                    lte?: string;
                    ne?: string;
                    between?: string;
                };
                /** @description e.g. totalSupplyUsd[gte]=100000 */
                "totalSupplyUsd[gte]"?: {
                    gt?: string;
                    gte?: string;
                    lt?: string;
                    lte?: string;
                    ne?: string;
                    between?: string;
                };
                /** @description e.g. totalSupplyUsd[gte]=100000 */
                "totalSupplyUsd[lt]"?: {
                    gt?: string;
                    gte?: string;
                    lt?: string;
                    lte?: string;
                    ne?: string;
                    between?: string;
                };
                /** @description e.g. totalSupplyUsd[gte]=100000 */
                "totalSupplyUsd[lte]"?: {
                    gt?: string;
                    gte?: string;
                    lt?: string;
                    lte?: string;
                    ne?: string;
                    between?: string;
                };
                /** @description e.g. totalSupplyUsd[gte]=100000 */
                "totalSupplyUsd[ne]"?: {
                    gt?: string;
                    gte?: string;
                    lt?: string;
                    lte?: string;
                    ne?: string;
                    between?: string;
                };
                /** @description e.g. totalSupplyUsd[gte]=100000 */
                "totalSupplyUsd[between]"?: {
                    gt?: string;
                    gte?: string;
                    lt?: string;
                    lte?: string;
                    ne?: string;
                    between?: string;
                };
                /** @description Reserve order[score] */
                "order[score]"?: "asc" | "desc" | "ASC" | "DESC";
                /** @description Reserve order[score] */
                "order[score][]"?: ("asc" | "desc" | "ASC" | "DESC")[];
                /** @description Reserve order[totalSupplyUsd] */
                "order[totalSupplyUsd]"?: "asc" | "desc" | "ASC" | "DESC";
                /** @description Reserve order[totalSupplyUsd] */
                "order[totalSupplyUsd][]"?: ("asc" | "desc" | "ASC" | "DESC")[];
                /** @description Reserve order[priceAgeSeconds] */
                "order[priceAgeSeconds]"?: "asc" | "desc" | "ASC" | "DESC";
                /** @description Reserve order[priceAgeSeconds] */
                "order[priceAgeSeconds][]"?: ("asc" | "desc" | "ASC" | "DESC")[];
                /** @description Reserve order[asset] */
                "order[asset]"?: "asc" | "desc" | "ASC" | "DESC";
                /** @description Reserve order[asset] */
                "order[asset][]"?: ("asc" | "desc" | "ASC" | "DESC")[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reserve collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["Reserve.jsonld"][];
                    };
                    "application/json": components["schemas"]["Reserve"][];
                };
            };
        };
    };
    api_reserves_address_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Reserve identifier */
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reserve resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Reserve.jsonld"];
                    "application/json": components["schemas"]["Reserve"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
