/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service health
         * @description Returns 200 when the database answers and the indexer refreshed every protocol within maxDataAgeSeconds, 503 otherwise. Point uptime monitors here.
         */
        get: operations["api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reserves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of Reserve resources.
         * @description Retrieves the collection of Reserve resources.
         */
        get: operations["api_reserves_get_collection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reserves/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a Reserve resource.
         * @description Retrieves a Reserve resource.
         */
        get: operations["api_reserves_address_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reserves/{address}/attestation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Signed health attestation of a reserve
         * @description Put `message`, `signature` and `publicKey` in an Ed25519 program instruction (e.g. Ed25519Program.createInstructionWithPublicKey) next to a call to oracle_guard. `issuedAt` is when the health was measured, not when it was signed, so a stopped indexer cannot produce fresh-looking attestations.
         */
        get: operations["api_reserves_addressattestation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of ReserveEvent resources.
         * @description Retrieves the collection of ReserveEvent resources.
         */
        get: operations["api_events_get_collection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a ReserveEvent resource.
         * @description Retrieves a ReserveEvent resource.
         */
        get: operations["api_events_id_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of ReserveIncident resources.
         * @description Retrieves the collection of ReserveIncident resources.
         */
        get: operations["api_incidents_get_collection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a ReserveIncident resource.
         * @description Retrieves a ReserveIncident resource.
         */
        get: operations["api_incidents_id_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reserves/{address}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of ReserveSnapshot resources.
         * @description Retrieves the collection of ReserveSnapshot resources.
         */
        get: operations["api_reserves_addresshistory_get_collection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a Stats resource.
         * @description Retrieves a Stats resource.
         */
        get: operations["api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of Vault resources.
         * @description Retrieves the collection of Vault resources.
         */
        get: operations["api_vaults_get_collection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vaults/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a Vault resource.
         * @description Retrieves a Vault resource.
         */
        get: operations["api_vaults_address_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CheckState: {
            code?: string;
            /** @enum {string} */
            severity?: "ok" | "info" | "warning" | "critical";
        };
        "CheckState.csv": {
            code?: string;
            /** @enum {string} */
            severity?: "ok" | "info" | "warning" | "critical";
        };
        "CheckState.jsonld": {
            code?: string;
            /** @enum {string} */
            severity?: "ok" | "info" | "warning" | "critical";
        };
        /** @description A representation of common errors. */
        Error: {
            /** @description A short, human-readable summary of the problem. */
            readonly title?: string | null;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            readonly detail?: string | null;
            /**
             * @default 400
             * @example 404
             */
            status: number | null;
            /** @description A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
            readonly instance?: string | null;
            /** @description A URI reference that identifies the problem type */
            readonly type?: string;
        };
        /** @description A representation of common errors. */
        "Error.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /** @description A short, human-readable summary of the problem. */
            readonly title?: string | null;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            readonly detail?: string | null;
            /**
             * @default 400
             * @example 404
             */
            status: number | null;
            /** @description A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
            readonly instance?: string | null;
            /** @description A URI reference that identifies the problem type */
            readonly type?: string;
            readonly description?: string | null;
        };
        /** @description Whether the database answers and every protocol was refreshed recently. */
        Health: {
            /** @description "ok" or "degraded". */
            status?: string;
            /** @description "ok" or "unreachable". */
            database?: string;
            /** @description Protocols not refreshed within this many seconds make the service degraded. */
            maxDataAgeSeconds?: number;
            protocols?: components["schemas"]["ProtocolFreshness"][];
        };
        /** @description Whether the database answers and every protocol was refreshed recently. */
        "Health.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /** @description "ok" or "degraded". */
            status?: string;
            /** @description "ok" or "unreachable". */
            database?: string;
            /** @description Protocols not refreshed within this many seconds make the service degraded. */
            maxDataAgeSeconds?: number;
            protocols?: components["schemas"]["ProtocolFreshness.jsonld"][];
        };
        HealthCheck: {
            /** @description e.g. STALE, NO_FALLBACK, NO_ORACLE, DEPRECATED_PROVIDER, EMPTY_PRICE_ENTRY, SOURCES_DIVERGE, MARKET_CLOSED. */
            code?: string;
            /** @enum {string} */
            severity?: "ok" | "info" | "warning" | "critical";
            message?: string;
        };
        "HealthCheck.csv": {
            /** @description e.g. STALE, NO_FALLBACK, NO_ORACLE, DEPRECATED_PROVIDER, EMPTY_PRICE_ENTRY, SOURCES_DIVERGE, MARKET_CLOSED. */
            code?: string;
            /** @enum {string} */
            severity?: "ok" | "info" | "warning" | "critical";
            message?: string;
        };
        "HealthCheck.jsonld": {
            /** @description e.g. STALE, NO_FALLBACK, NO_ORACLE, DEPRECATED_PROVIDER, EMPTY_PRICE_ENTRY, SOURCES_DIVERGE, MARKET_CLOSED. */
            code?: string;
            /** @enum {string} */
            severity?: "ok" | "info" | "warning" | "critical";
            message?: string;
        };
        HydraCollectionBaseSchema: components["schemas"]["HydraCollectionBaseSchemaNoPagination"] & {
            /**
             * @example {
             *       "@id": "string",
             *       "@type": "string",
             *       "first": "string",
             *       "last": "string",
             *       "previous": "string",
             *       "next": "string"
             *     }
             */
            view?: {
                /** Format: iri-reference */
                "@id"?: string;
                "@type"?: string;
                /** Format: iri-reference */
                first?: string | null;
                /** Format: iri-reference */
                last?: string | null;
                /** Format: iri-reference */
                previous?: string | null;
                /** Format: iri-reference */
                next?: string | null;
            };
        };
        HydraCollectionBaseSchemaNoPagination: {
            totalItems?: number;
            search?: {
                "@type"?: string;
                template?: string;
                variableRepresentation?: string;
                mapping?: {
                    "@type"?: string;
                    variable?: string;
                    property?: string | null;
                    required?: boolean;
                }[];
            };
        };
        HydraItemBaseSchema: {
            "@context"?: string | ({
                "@vocab": string;
                /** @enum {string} */
                hydra: "http://www.w3.org/ns/hydra/core#";
            } & {
                [key: string]: unknown;
            });
            "@id": string;
            "@type": string;
        };
        MarketRef: {
            /** @description Lending market address on Solana. */
            address?: string;
            /** @description Name shown by the protocol's own app; null for unlisted (permissionless) markets. */
            name?: string | null;
        };
        "MarketRef.csv": {
            /** @description Lending market address on Solana. */
            address?: string;
            /** @description Name shown by the protocol's own app; null for unlisted (permissionless) markets. */
            name?: string | null;
        };
        "MarketRef.jsonld": {
            /** @description Lending market address on Solana. */
            address?: string;
            /** @description Name shown by the protocol's own app; null for unlisted (permissionless) markets. */
            name?: string | null;
        };
        OracleAccounts: {
            /** @description Scope price account (Kamino's oracle aggregator). */
            scopePrices?: string | null;
            /** @description Entries of the Scope price account multiplied together to get the price. */
            scopeChain?: number[];
            pyth?: string | null;
            switchboard?: string | null;
            /** @description Oracle account that chains several sources (Jupiter Lend). */
            oracle?: string | null;
            /** @description Sources of that oracle, each multiplied or divided into the price. */
            sources?: components["schemas"]["OracleSourceRef"][];
        };
        "OracleAccounts.csv": {
            /** @description Scope price account (Kamino's oracle aggregator). */
            scopePrices?: string | null;
            /** @description Entries of the Scope price account multiplied together to get the price. */
            scopeChain?: number[];
            pyth?: string | null;
            switchboard?: string | null;
            /** @description Oracle account that chains several sources (Jupiter Lend). */
            oracle?: string | null;
            /** @description Sources of that oracle, each multiplied or divided into the price. */
            sources?: components["schemas"]["OracleSourceRef.csv"][];
        };
        "OracleAccounts.jsonld": {
            /** @description Scope price account (Kamino's oracle aggregator). */
            scopePrices?: string | null;
            /** @description Entries of the Scope price account multiplied together to get the price. */
            scopeChain?: number[];
            pyth?: string | null;
            switchboard?: string | null;
            /** @description Oracle account that chains several sources (Jupiter Lend). */
            oracle?: string | null;
            /** @description Sources of that oracle, each multiplied or divided into the price. */
            sources?: components["schemas"]["OracleSourceRef.jsonld"][];
        };
        OracleSourceRef: {
            /** @description Source type as named by the oracle program, e.g. "Chainlink", "Pyth", "StakePool". */
            type?: string;
            /** @description Source account on Solana. */
            account?: string;
        };
        "OracleSourceRef.csv": {
            /** @description Source type as named by the oracle program, e.g. "Chainlink", "Pyth", "StakePool". */
            type?: string;
            /** @description Source account on Solana. */
            account?: string;
        };
        "OracleSourceRef.jsonld": {
            /** @description Source type as named by the oracle program, e.g. "Chainlink", "Pyth", "StakePool". */
            type?: string;
            /** @description Source account on Solana. */
            account?: string;
        };
        PriceStatus: {
            /** @description Age of the oldest price in the reserve's price chain; null when it could not be read. */
            ageSeconds?: number | null;
            /** @description The protocol's own limit: older prices are rejected. */
            maxAgeSeconds?: number;
            /** @description True when the price is older than the protocol accepts; null when the age is unknown. */
            isStale?: boolean | null;
        };
        "PriceStatus.csv": {
            /** @description Age of the oldest price in the reserve's price chain; null when it could not be read. */
            ageSeconds?: number | null;
            /** @description The protocol's own limit: older prices are rejected. */
            maxAgeSeconds?: number;
            /** @description True when the price is older than the protocol accepts; null when the age is unknown. */
            isStale?: boolean | null;
        };
        "PriceStatus.jsonld": {
            /** @description Age of the oldest price in the reserve's price chain; null when it could not be read. */
            ageSeconds?: number | null;
            /** @description The protocol's own limit: older prices are rejected. */
            maxAgeSeconds?: number;
            /** @description True when the price is older than the protocol accepts; null when the age is unknown. */
            isStale?: boolean | null;
        };
        ProtocolFreshness: {
            /** @description e.g. "kamino". */
            protocol?: string;
            /** @description "ok" when refreshed within the limit, "stale" otherwise. */
            status?: string;
            /**
             * Format: date-time
             * @description When the indexer last saved this protocol; null if it never did.
             */
            lastCheckedAt?: string | null;
            ageSeconds?: number | null;
        };
        "ProtocolFreshness.jsonld": {
            /** @description e.g. "kamino". */
            protocol?: string;
            /** @description "ok" when refreshed within the limit, "stale" otherwise. */
            status?: string;
            /**
             * Format: date-time
             * @description When the indexer last saved this protocol; null if it never did.
             */
            lastCheckedAt?: string | null;
            ageSeconds?: number | null;
        };
        /** @description Lending reserves with their oracle health, filterable and sortable. */
        Reserve: {
            /** @description Reserve / bank account address on Solana. */
            address?: string;
            /** @description Lending protocol, e.g. "kamino". */
            protocol?: string;
            /** @description Token symbol as configured by the protocol, e.g. "SOL". */
            asset?: string;
            mint?: string;
            market?: components["schemas"]["MarketRef"];
            /** @description active, obsolete or hidden. */
            status?: string;
            /** @description Deposited value (available + borrowed) in USD, at the protocol's last stored price. */
            totalSupplyUsd?: number;
            /** @description 0 (broken) to 100 (healthy). */
            score?: number;
            /**
             * @description Worst severity among the failed checks, or "ok" when none failed.
             * @enum {string}
             */
            severity?: "ok" | "info" | "warning" | "critical";
            price?: components["schemas"]["PriceStatus"];
            /** @description Oracle providers the price ultimately comes from, e.g. ["PythLazer", "Chainlink"]. */
            providers?: string[];
            checks?: components["schemas"]["HealthCheck"][];
            oracleAccounts?: components["schemas"]["OracleAccounts"];
            /** Format: date-time */
            checkedAt?: string;
        };
        /** @description Lending reserves with their oracle health, filterable and sortable. */
        "Reserve.csv": {
            /** @description Reserve / bank account address on Solana. */
            address?: string;
            /** @description Lending protocol, e.g. "kamino". */
            protocol?: string;
            /** @description Token symbol as configured by the protocol, e.g. "SOL". */
            asset?: string;
            mint?: string;
            market?: components["schemas"]["MarketRef.csv"];
            /** @description active, obsolete or hidden. */
            status?: string;
            /** @description Deposited value (available + borrowed) in USD, at the protocol's last stored price. */
            totalSupplyUsd?: number;
            /** @description 0 (broken) to 100 (healthy). */
            score?: number;
            /**
             * @description Worst severity among the failed checks, or "ok" when none failed.
             * @enum {string}
             */
            severity?: "ok" | "info" | "warning" | "critical";
            price?: components["schemas"]["PriceStatus.csv"];
            /** @description Oracle providers the price ultimately comes from, e.g. ["PythLazer", "Chainlink"]. */
            providers?: string[];
            checks?: components["schemas"]["HealthCheck.csv"][];
            oracleAccounts?: components["schemas"]["OracleAccounts.csv"];
            /** Format: date-time */
            checkedAt?: string;
        };
        /** @description Lending reserves with their oracle health, filterable and sortable. */
        "Reserve.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /** @description Reserve / bank account address on Solana. */
            address?: string;
            /** @description Lending protocol, e.g. "kamino". */
            protocol?: string;
            /** @description Token symbol as configured by the protocol, e.g. "SOL". */
            asset?: string;
            mint?: string;
            market?: components["schemas"]["MarketRef.jsonld"];
            /** @description active, obsolete or hidden. */
            status?: string;
            /** @description Deposited value (available + borrowed) in USD, at the protocol's last stored price. */
            totalSupplyUsd?: number;
            /** @description 0 (broken) to 100 (healthy). */
            score?: number;
            /**
             * @description Worst severity among the failed checks, or "ok" when none failed.
             * @enum {string}
             */
            severity?: "ok" | "info" | "warning" | "critical";
            price?: components["schemas"]["PriceStatus.jsonld"];
            /** @description Oracle providers the price ultimately comes from, e.g. ["PythLazer", "Chainlink"]. */
            providers?: string[];
            checks?: components["schemas"]["HealthCheck.jsonld"][];
            oracleAccounts?: components["schemas"]["OracleAccounts.jsonld"];
            /** Format: date-time */
            checkedAt?: string;
        };
        /** @description The reserve's latest health, signed for the oracle_guard program. */
        ReserveAttestation: {
            /** @description Reserve / bank / vault address. */
            address?: string;
            /** @description 0 (broken) to 100 (healthy). */
            score?: number;
            /**
             * @description Worst severity among the failed checks, or "ok"; signed as 0 ok, 1 info, 2 warning, 3 critical.
             * @enum {string}
             */
            severity?: "ok" | "info" | "warning" | "critical";
            /** @description Age of the oldest price at `issuedAt`; null if it could not be read (signed as 0xFFFFFFFF). */
            priceAgeSeconds?: number | null;
            /**
             * Format: date-time
             * @description When the health was measured.
             */
            issuedAt?: string;
            /** @description The 54-byte attestation message, base64. */
            message?: string;
            /** @description Ed25519 signature of `message`, base64. */
            signature?: string;
            /** @description Signing key, Base58: must match the authority in oracle_guard's config. */
            publicKey?: string;
        };
        /** @description The reserve's latest health, signed for the oracle_guard program. */
        "ReserveAttestation.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /** @description Reserve / bank / vault address. */
            address?: string;
            /** @description 0 (broken) to 100 (healthy). */
            score?: number;
            /**
             * @description Worst severity among the failed checks, or "ok"; signed as 0 ok, 1 info, 2 warning, 3 critical.
             * @enum {string}
             */
            severity?: "ok" | "info" | "warning" | "critical";
            /** @description Age of the oldest price at `issuedAt`; null if it could not be read (signed as 0xFFFFFFFF). */
            priceAgeSeconds?: number | null;
            /**
             * Format: date-time
             * @description When the health was measured.
             */
            issuedAt?: string;
            /** @description The 54-byte attestation message, base64. */
            message?: string;
            /** @description Ed25519 signature of `message`, base64. */
            signature?: string;
            /** @description Signing key, Base58: must match the authority in oracle_guard's config. */
            publicKey?: string;
        };
        /** @description Health changes, newest first. */
        ReserveEvent: {
            id?: string;
            /** @description Reserve / bank / vault address on Solana. */
            reserve?: string;
            protocol?: string;
            asset?: string;
            /** @description Null for markets not listed in the protocol's own app. */
            marketName?: string | null;
            /**
             * Format: date-time
             * @description When the new state was first seen. The event is recorded a few minutes later, once the change has lasted.
             */
            occurredAt?: string;
            /** @enum {string} */
            direction?: "degraded" | "recovered" | "changed";
            /**
             * @description Worst severity after the change, or "ok" when no check fails any more.
             * @enum {string}
             */
            severity?: "ok" | "info" | "warning" | "critical";
            previousScore?: number;
            score?: number;
            /** @description Checks that started failing. */
            started?: components["schemas"]["CheckState"][];
            /** @description Checks that stopped failing. */
            resolved?: components["schemas"]["CheckState"][];
            /** @description Every failed check after the change. */
            checks?: components["schemas"]["CheckState"][];
            /** @description Supply in USD when the change happened. */
            totalSupplyUsd?: number;
        };
        /** @description Health changes, newest first. */
        "ReserveEvent.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            id?: string;
            /** @description Reserve / bank / vault address on Solana. */
            reserve?: string;
            protocol?: string;
            asset?: string;
            /** @description Null for markets not listed in the protocol's own app. */
            marketName?: string | null;
            /**
             * Format: date-time
             * @description When the new state was first seen. The event is recorded a few minutes later, once the change has lasted.
             */
            occurredAt?: string;
            /** @enum {string} */
            direction?: "degraded" | "recovered" | "changed";
            /**
             * @description Worst severity after the change, or "ok" when no check fails any more.
             * @enum {string}
             */
            severity?: "ok" | "info" | "warning" | "critical";
            previousScore?: number;
            score?: number;
            /** @description Checks that started failing. */
            started?: components["schemas"]["CheckState.jsonld"][];
            /** @description Checks that stopped failing. */
            resolved?: components["schemas"]["CheckState.jsonld"][];
            /** @description Every failed check after the change. */
            checks?: components["schemas"]["CheckState.jsonld"][];
            /** @description Supply in USD when the change happened. */
            totalSupplyUsd?: number;
        };
        /** @description Incidents, most recent start first. */
        ReserveIncident: {
            id?: string;
            /** @description Reserve / bank / vault address on Solana. */
            reserve?: string;
            protocol?: string;
            asset?: string;
            marketName?: string | null;
            /** Format: date-time */
            startedAt?: string;
            /**
             * @description True when the reserve was already failing when OracleCanary started tracking it: the start is
             *     then worked out from the age of its price.
             */
            startEstimated?: boolean;
            /**
             * Format: date-time
             * @description Null while the incident is ongoing.
             */
            endedAt?: string | null;
            /** @description Length of the incident in seconds; null while it is ongoing. */
            durationSeconds?: number | null;
            /** @description The critical checks when the incident started, plus MARKET_CLOSED (info) if the stock market was closed. */
            checks?: components["schemas"]["CheckState"][];
            /** @description Largest supply exposed during the incident, in USD. */
            totalSupplyUsd?: number;
        };
        /** @description Incidents, most recent start first. */
        "ReserveIncident.csv": {
            id?: string;
            /** @description Reserve / bank / vault address on Solana. */
            reserve?: string;
            protocol?: string;
            asset?: string;
            marketName?: string | null;
            /** Format: date-time */
            startedAt?: string;
            /**
             * @description True when the reserve was already failing when OracleCanary started tracking it: the start is
             *     then worked out from the age of its price.
             */
            startEstimated?: boolean;
            /**
             * Format: date-time
             * @description Null while the incident is ongoing.
             */
            endedAt?: string | null;
            /** @description Length of the incident in seconds; null while it is ongoing. */
            durationSeconds?: number | null;
            /** @description The critical checks when the incident started, plus MARKET_CLOSED (info) if the stock market was closed. */
            checks?: components["schemas"]["CheckState.csv"][];
            /** @description Largest supply exposed during the incident, in USD. */
            totalSupplyUsd?: number;
        };
        /** @description Incidents, most recent start first. */
        "ReserveIncident.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            id?: string;
            /** @description Reserve / bank / vault address on Solana. */
            reserve?: string;
            protocol?: string;
            asset?: string;
            marketName?: string | null;
            /** Format: date-time */
            startedAt?: string;
            /**
             * @description True when the reserve was already failing when OracleCanary started tracking it: the start is
             *     then worked out from the age of its price.
             */
            startEstimated?: boolean;
            /**
             * Format: date-time
             * @description Null while the incident is ongoing.
             */
            endedAt?: string | null;
            /** @description Length of the incident in seconds; null while it is ongoing. */
            durationSeconds?: number | null;
            /** @description The critical checks when the incident started, plus MARKET_CLOSED (info) if the stock market was closed. */
            checks?: components["schemas"]["CheckState.jsonld"][];
            /** @description Largest supply exposed during the incident, in USD. */
            totalSupplyUsd?: number;
        };
        /** @description Hourly health of one reserve, newest first by default. Empty for unknown reserves and unlisted markets. */
        ReserveSnapshot: {
            address?: string;
            /**
             * Format: date-time
             * @description Start of the hour, in UTC.
             */
            hour?: string;
            /** @description Lowest score during the hour, 0 (broken) to 100 (healthy). */
            score?: number;
            /**
             * @description Worst severity among the failed checks, or "ok" when none failed.
             * @enum {string}
             */
            severity?: "ok" | "info" | "warning" | "critical";
            /** @description Age of the price the protocol would use, in seconds; null when unknown. */
            priceAgeSeconds?: number | null;
            totalSupplyUsd?: number;
            checks?: components["schemas"]["CheckState"][];
        };
        /** @description Hourly health of one reserve, newest first by default. Empty for unknown reserves and unlisted markets. */
        "ReserveSnapshot.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            address?: string;
            /**
             * Format: date-time
             * @description Start of the hour, in UTC.
             */
            hour?: string;
            /** @description Lowest score during the hour, 0 (broken) to 100 (healthy). */
            score?: number;
            /**
             * @description Worst severity among the failed checks, or "ok" when none failed.
             * @enum {string}
             */
            severity?: "ok" | "info" | "warning" | "critical";
            /** @description Age of the price the protocol would use, in seconds; null when unknown. */
            priceAgeSeconds?: number | null;
            totalSupplyUsd?: number;
            checks?: components["schemas"]["CheckState.jsonld"][];
        };
        /** @description How many wallets are watched through the Telegram bot, and the value in them. */
        Stats: {
            /** @description Distinct wallets watched by at least one chat. */
            walletsWatched?: number;
            /** @description Deposits plus loans in those wallets at their last check, in USD. */
            valueWatchedUsd?: number;
        };
        /** @description How many wallets are watched through the Telegram bot, and the value in them. */
        "Stats.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /** @description Distinct wallets watched by at least one chat. */
            walletsWatched?: number;
            /** @description Deposits plus loans in those wallets at their last check, in USD. */
            valueWatchedUsd?: number;
        };
        /** @description Kamino curator vaults, largest first. */
        Vault: {
            /** @description Vault state account address on Solana. */
            address?: string;
            /** @description Name shown by Kamino, e.g. "Steakhouse USDC". */
            name?: string;
            /** @description Curator recognised in the name, e.g. "Steakhouse", or null. */
            curator?: string | null;
            /** @description Deposit token symbol, e.g. "USDC". */
            token?: string | null;
            /** @description Deposits in USD: allocations plus idle funds. */
            totalUsd?: number;
            /** @description Deposits not lent to any reserve, in USD. */
            idleUsd?: number;
            /**
             * @description USD lent into a reserve that has a critical check, or into a market where another asset
             *     (the collateral borrowers post) has one: while its price is unusable or wrong, bad loans
             *     cannot be liquidated and losses fall on lenders such as this vault.
             */
            atRiskUsd?: number;
            /** @description USD in reserves whose own worst check is a warning (e.g. no fallback oracle). */
            warningUsd?: number;
            /**
             * @description Worst severity among the reserves the vault lends to and their markets' collateral.
             * @enum {string}
             */
            worstSeverity?: "ok" | "info" | "warning" | "critical";
            /** @description Largest first. */
            allocations?: components["schemas"]["VaultAllocation"][];
            /** Format: date-time */
            checkedAt?: string;
        };
        /** @description Kamino curator vaults, largest first. */
        "Vault.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /** @description Vault state account address on Solana. */
            address?: string;
            /** @description Name shown by Kamino, e.g. "Steakhouse USDC". */
            name?: string;
            /** @description Curator recognised in the name, e.g. "Steakhouse", or null. */
            curator?: string | null;
            /** @description Deposit token symbol, e.g. "USDC". */
            token?: string | null;
            /** @description Deposits in USD: allocations plus idle funds. */
            totalUsd?: number;
            /** @description Deposits not lent to any reserve, in USD. */
            idleUsd?: number;
            /**
             * @description USD lent into a reserve that has a critical check, or into a market where another asset
             *     (the collateral borrowers post) has one: while its price is unusable or wrong, bad loans
             *     cannot be liquidated and losses fall on lenders such as this vault.
             */
            atRiskUsd?: number;
            /** @description USD in reserves whose own worst check is a warning (e.g. no fallback oracle). */
            warningUsd?: number;
            /**
             * @description Worst severity among the reserves the vault lends to and their markets' collateral.
             * @enum {string}
             */
            worstSeverity?: "ok" | "info" | "warning" | "critical";
            /** @description Largest first. */
            allocations?: components["schemas"]["VaultAllocation.jsonld"][];
            /** Format: date-time */
            checkedAt?: string;
        };
        VaultAllocation: {
            /** @description Reserve address. */
            reserve?: string;
            asset?: string;
            marketName?: string | null;
            /** @description Value the vault has in this reserve, in USD. */
            usd?: number;
            /** @description Share of the vault, 0 to 1. */
            share?: number;
            /**
             * @description The reserve's worst open check, or "ok".
             * @enum {string}
             */
            severity?: "ok" | "info" | "warning" | "critical";
            score?: number;
            /** @description The reserve's most severe check message, or null when healthy. */
            mainIssue?: string | null;
            /**
             * @description Other assets in the same market with a critical check, e.g. "FWDI: Price is 226140s old…":
             *     collateral whose price cannot be used, so loans against it cannot be liquidated.
             */
            collateralIssues?: string[];
        };
        "VaultAllocation.jsonld": {
            /** @description Reserve address. */
            reserve?: string;
            asset?: string;
            marketName?: string | null;
            /** @description Value the vault has in this reserve, in USD. */
            usd?: number;
            /** @description Share of the vault, 0 to 1. */
            share?: number;
            /**
             * @description The reserve's worst open check, or "ok".
             * @enum {string}
             */
            severity?: "ok" | "info" | "warning" | "critical";
            score?: number;
            /** @description The reserve's most severe check message, or null when healthy. */
            mainIssue?: string | null;
            /**
             * @description Other assets in the same market with a critical check, e.g. "FWDI: Price is 226140s old…":
             *     collateral whose price cannot be used, so loans against it cannot be liquidated.
             */
            collateralIssues?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Health.jsonld"];
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Degraded: data is stale, or the database is unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_reserves_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
                /** @description The number of items per page */
                itemsPerPage?: number;
                /** @description Lending protocol */
                protocol?: "kamino" | "marginfi" | "jupiter-lend";
                /** @description Lending market address */
                market?: string;
                /** @description Part of the market name, case-insensitive */
                marketName?: string;
                /** @description true: only markets listed in the protocol's own app. Unlisted (permissionless) markets can hold tokens with arbitrary prices. */
                listed?: boolean;
                /** @description Part of the asset symbol, case-insensitive */
                asset?: string;
                /** @description Reserve status */
                status?: "active" | "obsolete" | "hidden" | "unknown";
                /** @description Only reserves failing this check, e.g. DEPRECATED_PROVIDER (still depending on a shut-down oracle such as Switchboard), STALE or NO_FALLBACK */
                check?: string;
                /** @description Only reserves whose price depends on this source, as listed in `providers`, e.g. Pyth, PythLazer, Chainlink, ChainlinkDataStreams or SwitchboardOnDemand */
                provider?: string;
                /** @description Score greater than */
                "score[gt]"?: number;
                /** @description Score greater than or equal to */
                "score[gte]"?: number;
                /** @description Score less than, e.g. score[lt]=100 for reserves with any issue */
                "score[lt]"?: number;
                /** @description Score less than or equal to */
                "score[lte]"?: number;
                /** @description Supply greater than, in USD */
                "totalSupplyUsd[gt]"?: number;
                /** @description Supply greater than or equal to, in USD, e.g. 1000000 */
                "totalSupplyUsd[gte]"?: number;
                /** @description Supply less than, in USD */
                "totalSupplyUsd[lt]"?: number;
                /** @description Supply less than or equal to, in USD */
                "totalSupplyUsd[lte]"?: number;
                /** @description Sort by score */
                "order[score]"?: "asc" | "desc";
                /** @description Sort by supply */
                "order[totalSupplyUsd]"?: "asc" | "desc";
                /** @description Sort by price age */
                "order[priceAgeSeconds]"?: "asc" | "desc";
                /** @description Sort by asset symbol */
                "order[asset]"?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reserve collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["Reserve.jsonld"][];
                    };
                    "application/json": components["schemas"]["Reserve"][];
                    "text/csv": components["schemas"]["Reserve.csv"][];
                };
            };
        };
    };
    api_reserves_address_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Reserve identifier */
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reserve resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Reserve.jsonld"];
                    "application/json": components["schemas"]["Reserve"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_reserves_addressattestation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ReserveAttestation identifier */
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed attestation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ReserveAttestation.jsonld"];
                    "application/json": components["schemas"]["ReserveAttestation"];
                };
            };
            /** @description No reserve with this address */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Signing is not configured on this server */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_events_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
                /** @description The number of items per page */
                itemsPerPage?: number;
                /** @description Only events recorded after the event with this id. Ids only grow, so pollers can pass the highest id they have seen to get each event once. */
                "id[gt]"?: number;
                /** @description Lending protocol */
                protocol?: "kamino" | "marginfi" | "jupiter-lend";
                /** @description Reserve address */
                reserve?: string;
                /** @description Part of the asset symbol, case-insensitive */
                asset?: string;
                /** @description true: only markets listed in the protocol's own app */
                listed?: boolean;
                /** @description Changes that started at or after this UTC time, e.g. 2026-09-27T00:00:00Z */
                "occurredAt[after]"?: string;
                /** @description Changes that started at or before this UTC time */
                "occurredAt[before]"?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ReserveEvent collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["ReserveEvent.jsonld"][];
                    };
                    "application/json": components["schemas"]["ReserveEvent"][];
                };
            };
        };
    };
    api_events_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ReserveEvent identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ReserveEvent resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ReserveEvent.jsonld"];
                    "application/json": components["schemas"]["ReserveEvent"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_incidents_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
                /** @description The number of items per page */
                itemsPerPage?: number;
                /** @description Lending protocol */
                protocol?: "kamino" | "marginfi" | "jupiter-lend";
                /** @description Reserve address */
                reserve?: string;
                /** @description Part of the asset symbol, case-insensitive */
                asset?: string;
                /** @description true: only incidents that ended; false: only ongoing ones */
                resolved?: boolean;
                /** @description Largest exposure at least this many USD, e.g. 1 to leave out empty reserves */
                "totalSupplyUsd[gte]"?: number;
                /** @description Incidents that started at or after this UTC time, e.g. 2026-09-27T00:00:00Z */
                "startedAt[after]"?: string;
                /** @description Incidents that started at or before this UTC time */
                "startedAt[before]"?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ReserveIncident collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["ReserveIncident.jsonld"][];
                    };
                    "application/json": components["schemas"]["ReserveIncident"][];
                    "text/csv": components["schemas"]["ReserveIncident.csv"][];
                };
            };
        };
    };
    api_incidents_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ReserveIncident identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ReserveIncident resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ReserveIncident.jsonld"];
                    "application/json": components["schemas"]["ReserveIncident"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_reserves_addresshistory_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
                /** @description The number of items per page */
                itemsPerPage?: number;
                /** @description Hours starting at or after this UTC time, e.g. 2026-09-27T00:00:00Z */
                "hour[after]"?: string;
                /** @description Hours starting at or before this UTC time */
                "hour[before]"?: string;
                /** @description asc for charts (oldest first) */
                "order[hour]"?: "asc" | "desc";
            };
            header?: never;
            path: {
                /** @description ReserveHealthHourly identifier */
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ReserveSnapshot collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["ReserveSnapshot.jsonld"][];
                    };
                    "application/json": components["schemas"]["ReserveSnapshot"][];
                };
            };
        };
    };
    api_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stats resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Stats.jsonld"];
                    "application/json": components["schemas"]["Stats"];
                };
            };
        };
    };
    api_vaults_get_collection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vault collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchemaNoPagination"] & {
                        member: components["schemas"]["Vault.jsonld"][];
                    };
                    "application/json": components["schemas"]["Vault"][];
                };
            };
        };
    };
    api_vaults_address_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Vault identifier */
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vault resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Vault.jsonld"];
                    "application/json": components["schemas"]["Vault"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
