<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260927210608 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE reserve_health_hourly DROP CONSTRAINT reserve_health_hourly_pkey');
        $this->addSql('ALTER TABLE reserve_health_hourly ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX uniq_reserve_health_hourly_sample ON reserve_health_hourly (address, hour)');
        $this->addSql('ALTER TABLE reserve_health_hourly ADD PRIMARY KEY (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE reserve_health_hourly DROP CONSTRAINT reserve_health_hourly_pkey');
        $this->addSql('DROP INDEX uniq_reserve_health_hourly_sample');
        $this->addSql('ALTER TABLE reserve_health_hourly DROP id');
        $this->addSql('ALTER TABLE reserve_health_hourly ADD PRIMARY KEY (address, hour)');
    }
}
