<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260927193324 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE reserve_health_event (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, address VARCHAR(44) NOT NULL, protocol VARCHAR(32) NOT NULL, asset VARCHAR(64) NOT NULL, market_name VARCHAR(120) DEFAULT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, previous_score SMALLINT NOT NULL, score SMALLINT NOT NULL, previous_checks JSON NOT NULL, checks JSON NOT NULL, total_supply_usd DOUBLE PRECISION NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_reserve_health_event_occurred ON reserve_health_event (occurred_at)');
        $this->addSql('CREATE INDEX idx_reserve_health_event_reserve ON reserve_health_event (address, occurred_at)');
        $this->addSql('CREATE TABLE reserve_health_hourly (address VARCHAR(44) NOT NULL, hour TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, protocol VARCHAR(32) NOT NULL, score SMALLINT NOT NULL, price_age_seconds INT DEFAULT NULL, total_supply_usd DOUBLE PRECISION NOT NULL, checks JSON NOT NULL, PRIMARY KEY (address, hour))');
        $this->addSql('CREATE INDEX idx_reserve_health_hourly_protocol ON reserve_health_hourly (protocol, hour)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE reserve_health_event');
        $this->addSql('DROP TABLE reserve_health_hourly');
    }
}
