<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Wallets that Telegram users watch, for per-wallet alerts sent by the indexer's bot.
 */
final class Version20260930221450 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Wallets watched through the Telegram bot, with what each chat was last told';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE wallet_watch (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, chat_id BIGINT NOT NULL, wallet VARCHAR(44) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_state JSON NOT NULL, last_usd DOUBLE PRECISION DEFAULT NULL, last_checked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_wallet_watch_wallet ON wallet_watch (wallet)');
        $this->addSql('CREATE UNIQUE INDEX uniq_wallet_watch_chat_wallet ON wallet_watch (chat_id, wallet)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE wallet_watch');
    }
}
