<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Changes to how listed reserves are priced, recorded by the indexer from one run to the next.
 */
final class Version20260930222258 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Configuration changes of listed reserves: new listings, price sources and price age limits';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE reserve_config_change (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, address VARCHAR(44) NOT NULL, protocol VARCHAR(32) NOT NULL, asset VARCHAR(64) NOT NULL, market_name VARCHAR(120) DEFAULT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, kind VARCHAR(20) NOT NULL, detail TEXT NOT NULL, before_value JSON DEFAULT NULL, after_value JSON DEFAULT NULL, total_supply_usd DOUBLE PRECISION NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_reserve_config_change_occurred ON reserve_config_change (occurred_at, id)');
        $this->addSql('CREATE INDEX idx_reserve_config_change_address ON reserve_config_change (address)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE reserve_config_change');
    }
}
