<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260927224033 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Incidents: periods a listed reserve was critical';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE reserve_incident (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, address VARCHAR(44) NOT NULL, protocol VARCHAR(32) NOT NULL, asset VARCHAR(64) NOT NULL, market_name VARCHAR(120) DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, start_estimated BOOLEAN NOT NULL, ended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, checks JSON NOT NULL, total_supply_usd DOUBLE PRECISION NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_reserve_incident_started ON reserve_incident (started_at, id)');
        $this->addSql('CREATE INDEX idx_reserve_incident_reserve ON reserve_incident (address, started_at)');
        $this->addSql('CREATE INDEX idx_reserve_incident_protocol ON reserve_incident (protocol, started_at)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE reserve_incident');
    }
}
