<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260927162523 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE lending_reserve (address VARCHAR(44) NOT NULL, protocol VARCHAR(32) NOT NULL, market VARCHAR(44) NOT NULL, market_name VARCHAR(120) DEFAULT NULL, asset VARCHAR(64) NOT NULL, mint VARCHAR(44) NOT NULL, status VARCHAR(16) NOT NULL, total_supply_usd DOUBLE PRECISION NOT NULL, max_age_price_seconds INT NOT NULL, price_age_seconds INT DEFAULT NULL, score SMALLINT NOT NULL, providers JSON NOT NULL, checks JSON NOT NULL, feeds JSON NOT NULL, checked_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (address))');
        $this->addSql('CREATE INDEX idx_lending_reserve_market ON lending_reserve (protocol, market)');
        $this->addSql('CREATE INDEX idx_lending_reserve_score ON lending_reserve (score)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE lending_reserve');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
